app:
  datasource:
    host: localhost
    port: 5432
    database: billing_engine
    username: yule
    password: Wc123123

logging:
  level:
    root: INFO
    com.maimai: DEBUG
    org.springframework.security: INFO
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB