server:
  port: 8080

spring:
  application:
    name: billing-calculation-engine
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${app.datasource.host}:${app.datasource.port}/${app.datasource.database}
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

# related to common -> properties -> JwtProperties
app:
  jwt:
    # has to be 32 chars to pass the JWA specification
    # "HMAC-SHA algorithms MUST have a size >= 256 bits"
    secret-key: VeryLongSecretKeyHereThatIsAtLeast32CharactersLong
    ttl: 86400000
  currency:
    USD: 1.43

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true